version: "2.2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: infra-elasticsearch
    ports:
      - 9200:9200
    networks:
      - elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
        test: curl -s http://localhost:9200 | grep -q 'missing authentication credentials'
        interval: 10s
        timeout: 10s
        retries: 5

volumes:
  esdata:
    driver: local

networks:
  elastic: